### ISSUE TITLE
Can't build from source for node v0.10

### ISSUE THREAD

**Issue by lpfy** [Azure/node-sqlserver#137]
Windows 2008 R2 64bit with node.js 32bit 0.10.15

Don't know what's wrong? should I use Win7 to build? If anyone build driver for node v10 successfully, could you please share with me?

C:\nodejs\mssql>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@0.10.15 | win32 | ia32
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\Users\lpfy\AppData\Roaming\npm\node_modules\nod
e-gyp\gyp\gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\nodejs\mssql\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\lpfy\AppData\Roaming\npm\node_modules\nod
e-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\lpfy\.node-gyp\0.10.15\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\lpfy\.node-gyp\0.10.15',
gyp info spawn args   '-Dmodule_root_dir=C:\nodejs\mssql',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\nodejs\mssql\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

C:\nodejs\mssql>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@0.10.15 | win32 | ia32
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
  stdafx.cpp
  Connection.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
C:\Users\lpfy.node-gyp\0.10.15\deps\v8\include\v8.h(179): warning C4506: no de
finition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Hand
le<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
  Column.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(201): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(201): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
  OdbcError.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
..\src\Column.cpp(163): warning C4244: '=' : conversion from 'const int64_t' to
 'SQLUSMALLINT', possible loss of data [C:\nodejs\mssql\build\sqlserver.vcxproj
]
..\src\Column.cpp(164): warning C4244: '=' : conversion from 'const int64_t' to
 'SQLUSMALLINT', possible loss of data [C:\nodejs\mssql\build\sqlserver.vcxproj
]
C:\Users\lpfy.node-gyp\0.10.15\deps\v8\include\v8.h(184): warning C4506: no de
finition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Hand
le<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
  Utility.cpp
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
C:\Users\lpfy.node-gyp\0.10.15\deps\v8\include\v8.h(179): warning C4506: no de
finition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Hand
le<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
  ResultSet.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
C:\Users\lpfy.node-gyp\0.10.15\deps\v8\include\v8.h(179): warning C4506: no de
finition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Hand
le<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
  OdbcOperation.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(201): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
  OdbcConnection.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\nodejs\mssql\build\sqlserver.vcxproj]
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
c:\nodejs\mssql\src\stdafx.h(43): warning C4005: 'interface' : macro redefiniti
on [C:\nodejs\mssql\build\sqlserver.vcxproj]
          C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objbase.h
  (199) : see previous definition of 'interface'
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(201): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(201): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [C:\nodejs\mssql\build\sqlserver.vcxproj]
          with
          [
              T=v8::Object
          ]
     Creating library C:\nodejs\mssql\build\Release\sqlserver.lib and object C:
  \nodejs\mssql\build\Release\sqlserver.exp
Connection.obj : error LNK2001: unresolved external symbol _SQLFreeHandle@8 [C:
\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLSetEnvAttr@1
6 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLMoreResults@
4 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLColAttribute
W@28 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLGetDiagRecW@
32 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLGetData@24 [
C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLAllocHandle@
12 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLExecDirectW@
12 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLBindParamete
r@40 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLSetConnectAt
trW@16 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLDescribeColW
@36 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLRowCount@8 [
C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLDriverConnec
tW@32 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLNumResultCol
s@8 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLFetch@4 [C:\
nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLDisconnect@4
 [C:\nodejs\mssql\build\sqlserver.vcxproj]
OdbcConnection.obj : error LNK2001: unresolved external symbol _SQLEndTran@12 [
C:\nodejs\mssql\build\sqlserver.vcxproj]
C:\nodejs\mssql\build\Release\sqlserver.node : fatal error LNK1120: 17 unresolv
ed externals [C:\nodejs\mssql\build\sqlserver.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\lpfy\AppData\Roaming\npm\nod
e_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\lpfy\AppData\Roaming\npm\node_modules\n
ode-gyp\bin\node-gyp.js" "build"
gyp ERR! cwd C:\nodejs\mssql
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok

C:\nodejs\mssql>

**Comment by Dilip9922** [comment]
Thank you it worked for me too :)
