### ISSUE TITLE
Query notifications

### ISSUE THREAD

**Issue by orand** [Azure/node-sqlserver#159]
I'd like to use node-sqlserver to subscribe to receive query notifications, but that doesn't appear to be supported. This feature would pair quite nicely with socket.io.

**Comment by jamesmstone** [comment]
+1 Any news?

**Comment by tvrprasad** [comment]
@jamesmstone  There is no active development on this project. Recommended driver for nodejs is https://github.com/tediousjs/tedious/ and there is active development on that project.

**Comment by jamesmstone** [comment]
Thanks
