### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by dsalcedo** [Azure/node-sqlserver#171]
This project is current maintained?

**Comment by arosca** [comment]
Any update?

**Comment by meet-bhagdev** [comment]
Hey guys, we still do not have a date penciled in. However it is definitely in the pipeline.
In the meanwhile use this document http://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-nodejs-simple-windows/ to use this driver.
We will have some more blogs in the coming weeks so keep an eye out
