### ISSUE TITLE
error install node-sqlserver in windows 8

### ISSUE THREAD

**Issue by gbelmm** [Azure/node-sqlserver#172]
help please

error:

npm WARN package.json app@0.0.0 No repository field.
npm WARN deprecated node-sqlserver@0.1.0: This package has been superseded by msnodesql.
npm WARN engine node-sqlserver@0.1.0: wanted: {"node":"0.6"} (current: {"node":"v0.10.29","npm":"1.4.14"})
/

> node-sqlserver@0.1.0 install C:\TODO\xampp3\xampp-portable\htdocs\erp\node_modules\node-sqlserver
> node-gyp rebuild

C:\TODO\xampp3\xampp-portable\htdocs\erp\node_modules\node-sqlserver>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
MSBUILD : error MSB4132: No se reconoce la versión de herramientas "2.0". Las versiones de herramientas disponibles son "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\TODO\xampp3\xampp-portable\htdocs\erp\node_modules\node-sqlserver
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! node-sqlserver@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sqlserver@0.1.0 install script.
npm ERR! This is most likely a problem with the node-sqlserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sqlserver
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "node-sqlserver"
npm ERR! cwd C:\TODO\xampp3\xampp-portable\htdocs\erp
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\TODO\xampp3\xampp-portable\htdocs\erp\npm-debug.log
npm ERR! not ok code 0

**Comment by chrisronline** [comment]
I think this can easily be solved by removing this: https://github.com/Azure/node-sqlserver/blob/master/package.json#L30
