### ISSUE TITLE
The state of node-sqlserver

### ISSUE THREAD

**Issue by futurechan** [Azure/node-sqlserver#173]
I am hoping to get an update on the state of this project. It seems there hasn't been a commit in about a year and there are several open pull requests.

**Comment by meet-bhagdev** [comment]
This driver is being updated and you should see some updates soon. In the meanwhile follow instructions here http://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-nodejs-simple-windows/.
We will have some detailed blogs coming up soon.

**Comment by futurechan** [comment]
@meet-bhagdev any status update? It seems others are asking the same thing #189.

**Comment by meet-bhagdev** [comment]
Hello @futurechan thanks for the question. The only status update is that we are hands down on getting the next version shipped. If you have any issues regarding the current driver I would love to help you out.
