### ISSUE TITLE
Use npm proxy for downloading driver

### ISSUE THREAD

**Issue by koenmetsu** [Azure/node-sqlserver#183]
Running npm install msnodesql behind a proxy results in 

> You are downloading Microsoft Driver for Node.js for SQL Server from
> Microsoft, the license agreement to which is available at
> http://download.microsoft.com/download/6/E/2/6E2D7972-E54D-45AA-
> 8AB6-41E616035147/EULA.rtf and in the project folder to which the
> software is downloaded. Check the package for additional dependencies, which
> may come with their own license agreement(s). Your use of the package and
> dependencies constitutes your acceptance of their license agreements. If
> you do not accept the license agreement(s), then delete the relevant
> components from your device.
> install.js: Error: getaddrinfo ENOTFOUND
> msnodesql@0.2.1 node_modules\msnodesql

Possible solutions:
- Using the npm proxy
- Pass argument as a flag?

**Comment by meet-bhagdev** [comment]
Hmm this is weird. The proxy seems to be protecting the addrinfo. Have you tried passing it as a flag?
