### ISSUE TITLE
Is there any simple complete example to follow?

### ISSUE THREAD

**Issue by vip30** [Azure/node-sqlserver#188]
I am newbie of node.js and we currently working with MSSQL.
so I wonder is there any example to download.
Thanks

**Comment by meet-bhagdev** [comment]
Hi vip30,
Absolutely there is. 
http://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-nodejs-simple-windows/
Let me know if this helps :) We have a more detailed blog coming up
