### ISSUE TITLE
Dead, or merely dormant?

### ISSUE THREAD

**Issue by oaustegard** [Azure/node-sqlserver#189]
Nearly 2 years without an update does not signal a healthy library.

Where does this fall compared to say https://github.com/pekim/tedious?

**Comment by JohnGreenan** [comment]
Dead.  
No action for a long time and no response to your post.
Shame, this could have helped with a project I have been working on.  Will have to use other routes to get data from MS SQL 2014 to node.

**Comment by meet-bhagdev** [comment]
Hello oaustegard.
We are currently working on the next node.js driver. Additionally we just updated some docs Azure.com.
http://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-nodejs-simple-windows/
It is a getting started simple doc. We are also working on a blog series which go deeper into using this driver.
Feel free to reach out to me if you have any questions about this driver.
Best,
Meet

**Comment by bzuillsmith** [comment]
Thanks @meet-bhagdev. Will the next node.js driver be open-source? Will it be continuing from the work in this repo? It'd be nice for some observable activity. MS SQL would be a great fit for some of my work, but hard to trust it'll be there when I need it in the future.

**Comment by meet-bhagdev** [comment]
The next node.js driver will be open source. We are still working on a cadence strategy for accepting pull requests. It will definitely build on on the codebase here. We now have a dedicated team here at Microsoft whose goal is to maintain SQL Server drivers. So if you need any help with the driver in the future feel free to reach out :)

**Comment by JohnGreenan** [comment]
That's great news.  When can we expect a release?  
I don't want to hijack this thread, but...

If there is a dedicated team at Microsoft looking after MS SQL Server drivers - could they please have a look at this blog post I wrote?
http://blog.alignment-systems.com/2015/04/microsoft-jdbc-40-and-41-driver-missing.html
Would be good to get the documentation for the JDBC driver included in the distribution...

**Comment by melote** [comment]
yeah, hope to release ASAP.

**Comment by justinfreitag** [comment]
bump :)

**Comment by meet-bhagdev** [comment]
@JohnGreenan : Unfortunately I can not give you a date but let me tell we are working on it as I type :)
For Java, here is some documentation
https://azure.microsoft.com/en-us/documentation/articles/sql-data-java-how-to-use-sql-database/

**Comment by tylersmith34** [comment]
Any update on the release date?  The current version is honestly a sorry excuse for an NPM module.  The whole point is not to have to build the plugin after download to get it to run.

**Comment by jcollum** [comment]
If this project is dormant **you should put that right at the top of the readme.md**.

**Comment by Lfsantos** [comment]
No, it’s not.  We are revamping it and will have a new release in the following months.

Thanks

**Comment by jcollum** [comment]
OK. But if this is another "it will only work on Windows" situation (like the officially supported MS SQL Node driver) there's no way I'll use it.

**Comment by meet-bhagdev** [comment]
Hello tylersmith34,
We are working in a newer version of the Node.js driver.  Right now, we are heads down working on the scheduling the next version of our Node.js and will let you know when it’s available.

**Comment by Lfsantos** [comment]
We will make it available to other OS'es too.

Sent from my iPhone

On Jul 14, 2015, at 10:13 AM, Justin Collum <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. But if this is another "it will only work on Windows" situation (like the officially supported MS SQL Node driver) there's no way I'll use it.

-

**Comment by jcollum** [comment]
Good news, thanks.

**Comment by MartinStava** [comment]
Any update on the release date of the driver?

**Comment by jcollum** [comment]
@MartinStava in the meantime you might want to have a look at Seriate.

**Comment by csucla2015** [comment]
@MartinStava @jcollum we are still working on a new release. In the meantime I highly encourage you look at msnodesqlv8:  https://www.npmjs.com/package/msnodesqlv8. Here is the Github repo: https://github.com/TimelordUK/node-sqlserver-v8

It is basically this driver but with latest node.js version compatibility, command line install experience, no dependencies and great performance. 

It is a fork of this project and we plan on using it as a base for our next version. Hope this helps and if you have any questions please let me know.

Thanks,
Meet

**Comment by meet-bhagdev** [comment]
@MartinStava @jcollum we are still working on a new release. In the meantime I highly encourage you look at msnodesqlv8: https://www.npmjs.com/package/msnodesqlv8. Here is the Github repo: https://github.com/TimelordUK/node-sqlserver-v8

It is basically this driver but with latest node.js version compatibility, command line install experience, no dependencies and great performance.

It is a fork of this project and we plan on using it as a base for our next version. Hope this helps and if you have any questions please let me know.

Thanks,
Meet

**Comment by MartinStava** [comment]
@meet-bhagdev @jcollum thank you very much, guys, for pointing me the right direction. I'll definitely give it a try.

**Comment by NoumanSaleem** [comment]
@meet-bhagdev thanks for the updates. Will the new module have linux support?

**Comment by chadbr** [comment]
Any word on this? Would like to see MSFT supporting their products on node...

**Comment by meet-bhagdev** [comment]
@chadbr : Have you had a chance to check out : https://github.com/TimelordUK/node-sqlserver-v8 ? This seems to fix several of the issues with this driver and shares the same core codebase. I also encourage you to check out https://github.com/patriksimek/node-mssql. We are working out a plan for the node.js driver and will keep you and the rest updated on Github.

**Comment by chadbr** [comment]
@meet-bhagdev thanks for the update. I've checked it out -- haven't had a chance to try it yet. Just trying to gauge an ETA, etc...

Thanks --

**Comment by meet-bhagdev** [comment]
Hello all,

We at SQL Server have been working hard on putting concerted efforts in training our engineering support team to support with open source drivers. We are pleased to inform you that we now support the [Tedious](https://github.com/pekim/tedious) driver. Considering that the Microsoft Node.js driver for SQL Server lacks support for the latest Node.js version, we recommend you to use Tedious for Node.js versions 0.8.x and above. 

We would also like to understand your use cases and requirements for the Microsoft SQL Server - Node.js driver for SQL Server. This will to enable us to help you better.

Thank you,
SQL Server team.

**Comment by chadbr** [comment]
That's great to hear.

Does this mean the MS driver is dead? @Lfsantos said last year it was still in progress...

Thanks, Chad

**Comment by meet-bhagdev** [comment]
@chadbr: It means that a lot of people use Tedious, in fact people use the following drivers with SQL. Our goal is to support customers using all the popular drivers from the list below beyond just the MSFT built ones :) 

![image](https://cloud.githubusercontent.com/assets/11928821/15981808/cb96cba4-2f2f-11e6-8067-2563c1226535.png)

**Comment by restored18** [comment]
So does Microsoft have any plans to release a Node specific SQL Server driver anymore? I've had success using the MS SQL driver for PHP and would like to see something similar in Node.js.

**Comment by chadbr** [comment]
@restored18 as far as I can tell - Tedious is the answer...

**Comment by restored18** [comment]
@chadbr @meet-bhagdev So does this mean Microsoft is putting engineering time into Tedious or is it just a general recommendation for Node users?

**Comment by LuisBosquez** [comment]
Hello @restored18,

Yes, Microsoft is now actively contributing to Tedious. A few of the things we have done already include the following PRs:

- [Connection class constructor keeps a reference of and modifies passed in config](https://github.com/tediousjs/tedious/pull/445)
- [NTLM authentication requires domain to be upper case](https://github.com/tediousjs/tedious/pull/417)
- [Fixed issues with Tedious not working with older versions of TDS protocol.](https://github.com/tediousjs/tedious/pull/420)
- [Multi-subnet failover in progress](https://github.com/tediousjs/tedious/pull/362)

We are also working on adding support for new features for SQL Server, starting with Windows Autentication:
Windows Integrated Authentication support in progress:

- https://github.com/tvrprasad/sspi-client
- https://github.com/tediousjs/tedious/pull/486

Please let me know if you have any questions 👍 

Thanks,
Luis

**Comment by restored18** [comment]
@LuisBosquez that's great to hear, I would like to use Node with SQL Server in the future so having a well supported driver is encouraging.

**Comment by LuisBosquez** [comment]
@restored18 Awesome! Make sure to check out our new samples website: [Build an app using SQL Server](http://aka.ms/sqldev) where we have our getting started samples, as well as all of our driver recommendations for each programming language.

**Comment by MrRoyce** [comment]
@LuisBosquez 

Hi - We are trying to use the library at https://github.com/tediousjs/node-mssql but are getting random connection pool timeout errors. There are many open issues on the connection pool and other error in that library as well as open PR's etc.

There is even a comment about 'someone from Microsoft' being interested in taking over the library:

https://github.com/tediousjs/node-mssql/issues/601#issuecomment-368275386

Can you help with this?  This is causing us major headaches in our production environment.

**Comment by David-Engel** [comment]
@MrRoyce 
Hi - I'm the current PM for the SQL Server drivers teams. I read the conversation you linked to. I had not seen it before and didn't realize node-mssql had been added to the tediousjs org. The conversation is good, though, as Microsoft officially supports and contributes to the [tedious](https://github.com/tediousjs/tedious) project for Node.js connections to SQL Server and we welcome any suggestions on how we can improve the Node.js experience connecting to SQL Server. If people are using something different due to limitations in tedious, those are good areas we can focus our efforts on improving the driver.

That said, I don't see Microsoft signing up to maintain two separate Node.js drivers at this time. As Arthur noted, that has a significant, non-zero cost to it. Ideally, either users migrate to tedious, or (something like this would be driven by Arthur as the tedious owner) tedious and node-mssql merge into a single entity that we continue to support.

Regards,
David

**Comment by MrRoyce** [comment]
@David-Engel thanks for the quick response!  Do you work with @arthurschreiber?

As you see from the other project, there are lots of folks struggling with the node-mssql library but are scared to switch because of its simple(r) API, connection pools, etc.  We are using it in production for several applications (Node.js, Docker) but the instability in the connection is making everyone here very frustrated.

Maybe a best case scenario for developers and Microsoft would be to upgrade the tedious driver to have the same API as the node-mssql library with fixes for the connection pool and other issues.  

If you can provide some clarity on the direction we should take, it would be greatly appreciated.

**Comment by David-Engel** [comment]
@MrRoyce I work for Microsoft with the team that contributes to tedious. @arthurschreiber owns the tedious open-source project and we work with him to maintain and improve it. We are happy to participate in conversations on the direction of tedious but we don't make the ultimate decisions there.

As for the direction you should take, I don't really know enough about node-mssql, your issues with it, and how hard it would be for you to migrate to tedious to make that call for you. I can say that Microsoft does officially support tedious and we help troubleshoot and respond to issues filed in the tedious repo. We are committed to helping customers succeed with the tedious driver.

Tedious is open-source and all contributors are welcome. If you have the ability, you can always propose an API layer in tedious to ease migration from node-mssql. 😃 

Regards,
David
