### ISSUE TITLE
Please provide binary releases through npm

### ISSUE THREAD

**Issue by beautifulcoder** [Azure/node-sqlserver#191]
I installed msnodelsql through Microsoft downloads. There are no instructions, just trial and error. After fiddling with it for about an hour, I got this weird error:

```
C:\Dev\HelloWorldNodeAzure\node_modules\msnodesql\lib\sqlserver:1
(function (exports, require, module, __filename, __dirname) { MZ∩┐╜
                                                            ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Dev\HelloWorldNodeAzure\node_modules\msnodesql\lib
\sqlserver.native.js:21:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

So, it would be awesome if we could just pull the binaries from npm and have it just work. I don't see much point in in providing a binary through a download when you have to manually integrate it with npm. Source packages you have to compile yourself is not a real option.

**Comment by meet-bhagdev** [comment]
Hi beatiful code please follow this blog post to install msnodesql : http://blogs.msdn.com/b/sqlphp/archive/2015/05/12/getting-started-with-node-js-and-microsoft-sql-server-and-azure-sql-database.aspx

**Comment by beautifulcoder** [comment]
Sorry, I don't think I was clear. What I would like to see is something like the [MongoDB Node.js driver](http://docs.mongodb.org/getting-started/node/client/):

- `npm install mongodb`, for example
- Runs on the latest version of Node.js
- No third party tools like Python or VC++ to set up

The entry level is set too high when you get locked into a specific version of Node.js. It also needs third party tools to compile, which doesn't make much sense.

**Comment by meet-bhagdev** [comment]
Thanks for the response. The next Node.js version is in the pipeline. That will be compatible with the latest node.js version.
Best,
Meet

**Comment by arthurschreiber** [comment]
@meet-bhagdev Any news on the next-gen mssql driver? I'm a maintainer of https://github.com/pekim/tedious, which is an open source, pure javascript mssql driver for Node.JS. I'd love to compare performance between the two and see how we compare to the "official" Microsoft Driver. :smile:

**Comment by meet-bhagdev** [comment]
Hello @arthurschreiber ,
It is great to hear from you. The only news I have is that it is in the pipeline and planned for release in the coming months, I can not share any dates with you, but I will let you know once we release :)

**Comment by diegobanuelos** [comment]
Last post was almost a year ago... any news?
