### ISSUE TITLE
I have built this driver using latest Node JS module API  / Visual Studio 2013

### ISSUE THREAD

**Issue by TimelordUK** [Azure/node-sqlserver#192]
reaching out to the authors of this driver - I appreciate a new version is in the pipeline but I needed something right now with integrated security that works with latest Node/V8 API.  

I have hence adapted this library and now have it up and running such that it passes all the tests and this will allow me to progress.  I cant help thinking this could benefit others in short term while the "official release" is still being worked on.  I have tested against latest Node server.

Could the authors of the this driver let me know if it is possible for me to provide this work under current license conditions.

I was considering adding support for stored procedure calls and possibly other features if their is demand from the community, I could potentially also provide x86 and x64 binary.

please let me know if this is of any interest and whether it is possible for me to publish code or even just the binaries.

thanks

**Comment by jkint** [comment]
From your description, it sounds as if this should be possible.  Before we accept contributions, we ask that you sign a Contributor License Agreement (CLA) and submit it.

Instructions on how to do this and more information can be found in the document at https://github.com/Azure/node-sqlserver/blob/master/CONTRIBUTING.md.

Thanks,

Jay Kint

**Comment by meet-bhagdev** [comment]
Hi @TimelordUK 
Thank you for reaching out. I am part of the engineering team who works on client drivers and connectors. Once you sign the CLA I would love to get in touch with you to understand some of your plans and see if we can help you out in any way I can. We are also working on the next version of this driver and it would be good to get some feedback from about the current one so that we can improve the next version.

Look forward to hearing from you.

Best,
Meet Bhagdev

**Comment by TimelordUK** [comment]
I am making reasonable progress.  I am working on stored procedure with input output parameters which is nearly finished.  After that I will try and add prepared statement and later batch insert.  I submitted my form is it approved ? Can I release the code or not?

**Comment by meet-bhagdev** [comment]
@TimelordUK The team has approved the form. You can release the code. Again, thank you for all the help.

**Comment by NoelAbrahams** [comment]
Is there a way to try out the new code?

**Comment by meet-bhagdev** [comment]
Hi @NoelAbrahams 

Please stay tuned as we do not have a significant update to share yet. 

Thanks,
Meet

**Comment by TimelordUK** [comment]
with regards to my branch of this code, I have now completed the work on stored procedures - I have introduced a new helper to fetch meta data on a proc - it will allow input/output parameters and captures return code.  I only support simply types, but may well add cursors later.  I intend to check my code into a new repository in coming days, something like node-sqlserver-v8.  I have tested with VS2013, 2015 compilers and latest Node JS.   I will then look to package into npm probably the binaries as most people wont want to build the code.  I intend to add other features over the coming months so stay tuned.

**Comment by TimelordUK** [comment]
https://github.com/TimelordUK/node-sqlserver-v8

guys, for anyone interested this repository for the new version of this driver which i have tried against the latest 0.12.7 build of node js.  I intend to release npm module shortly.

**Comment by meet-bhagdev** [comment]
Hi @TimelordUK,
This is fabulous! I am very excited to see this. Please let me know when you release the npm module. I would love to give it a shot.

Cheers,
Meet

**Comment by TimelordUK** [comment]
I have released a module, https://www.npmjs.com/package/msnodesqlv8 - it should not be necessary to compile it as I include binaries.   I also have a test version working against Node 4.0.0, it required just a couple lines of change.  I will release this in coming days and will then look at adding bulk insert.  Stay tuned.

**Comment by NoelAbrahams** [comment]
@meet-bhagdev,

> We are planning on releasing a new version on Windows and Linux in the coming months. Stay tuned.

Nothing seems to be happening on any front.
