### ISSUE TITLE
Impossible to install on Windows 8.1 Pro npm 3.3.8, node 4.2.1

### ISSUE THREAD

**Issue by everydev** [Azure/node-sqlserver#194]
npm install -g  msnodesql
...
npm ERR! Failed at the msnodesql@0.2.1 install script 'node scripts/install.js'.

below the debug files:
![npm_install_msnodesql_screen](https://cloud.githubusercontent.com/assets/8067440/11615917/52f45126-9c6d-11e5-94b8-fb300f82cf7f.PNG)
[npm_install_msnodesql.txt](https://github.com/Azure/node-sqlserver/files/53302/npm_install_msnodesql.txt)

**Comment by TimelordUK** [comment]
You can try msnodesqlv8 module which should run on latest node.
