### ISSUE TITLE
Unable to download msnodesql-0.2.1-v4.3-x64.msi

### ISSUE THREAD

**Issue by uthaman** [Azure/node-sqlserver#195]
When installing msnodesql, getting the below error.

install.js: Unable to download msnodesql-0.2.1-v4.3-x64.msi
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! msnodesql@0.2.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msnodesql@0.2.1 install script 'node scripts/install.js'.

npm ERR! This is most likely a problem with the msnodesql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls msnodesql
npm ERR! There is likely additional logging output above.
npm ERR! error rolling back Error: EBUSY: resource busy or locked, rmdir 'C:\nod
ejs\myapp\node_modules\msnodesql\test'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'C:
\nodejs\myapp\node_modules\msnodesql\test']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: 'C:\\nodejs\\myapp\\node_modules\\msnodesql\
\test' }

**Comment by meet-bhagdev** [comment]
@uthaman what version of Node.js are you using? This driver is only supported on 0.8.x
We are working on a refresh that will add support to latest Node.js versions.

**Comment by ginxwar** [comment]
@meet-bhagdev Do you have an ETA?  I have customers that need an official driver from Microsoft before I could proceed with my projects.

**Comment by uthaman** [comment]
I am using V 4.3.0. Closing this issue.

**Comment by meet-bhagdev** [comment]
@ginxwar : We do not have an ETA yet. I am curious to know what your thoughts are on - [node-mssql](https://github.com/patriksimek/node-mssql) and [Tedious](https://github.com/pekim/tedious)

@uthaman : Can an you share what steps did you follow to get the driver to work with v 4.3.0?

**Comment by uthaman** [comment]
It did not work with v 4.3.0, I am using node-mssql.

**Comment by ginxwar** [comment]
@meet-bhagdev I've been using [Tedious](https://github.com/pekim/tedious) and I'm not complaining.  But it would be nice to have an official driver from Microsoft.
