### ISSUE TITLE
Can i use this driver to connect with sal compact edition

### ISSUE THREAD

**Issue by RealTimeTech** [Azure/node-sqlserver#200]
1) Is it possible to read data from sql ce with node js.
2) Sql ce db file format .sdf
3) for that Microsoft .net  environment is mandatory?

Please help me out  and thanks in advance :)

**Comment by RealTimeTech** [comment]
Sorry not sal that is SQL compact edition.

**Comment by meet-bhagdev** [comment]
@David-Engel can help answer questions

**Comment by David-Engel** [comment]
@RealTimeTech 
1. Unfortunately, no. SQL CE only supports connections using ADO.NET or OLEDB. The Microsoft Driver for Node.js for SQL Server relies on the Microsoft ODBC Driver for SQL Server which cannot connect to SQL CE.
2 & 3. .sdf is simply the file format of a SQL CE database. It should not require .NET. However, if you choose to use ADO.NET, that does require .NET. If you choose OLEDB, that is generally used with C++ applications.
David
