### ISSUE TITLE
node-gyp build error

### ISSUE THREAD

**Issue by safiahh** [Azure/node-sqlserver#201]
when i run node-gyp build i got this error
C:\Users\Admin\nodeni>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Callbacks.cc
  Context.cc
..\src\Callbacks.cc(1): warning C4005: 'BUILDING_NODE_EXTENSION' : macro redefinition [C:\Users\Admin\nodeni\build\open
ni.vcxproj]
          command-line arguments :  see previous definition of 'BUILDING_NODE_EXTENSION'
..\src\Context.cc(1): warning C4005: 'BUILDING_NODE_EXTENSION' : macro redefinition [C:\Users\Admin\nodeni\build\openni
.vcxproj]
          command-line arguments :  see previous definition of 'BUILDING_NODE_EXTENSION'
c:\users\admin\nodeni\src\Context.h(50): error C2039: 'ObjectWrap' : is not a member of 'node' (..\src\Callbacks.cc) [C
:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(50): error C2504: 'ObjectWrap' : base class undefined (..\src\Callbacks.cc) [C:\Use
rs\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(85): error C2146: syntax error : missing ';' before identifier 'event_thread_' (..\
src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(85): error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(86): error C2146: syntax error : missing ';' before identifier 'uv_async_joint_chan
ge_callback_' (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(86): error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(87): error C2146: syntax error : missing ';' before identifier 'uv_async_error_call
back_' (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(87): error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(88): error C2146: syntax error : missing ';' before identifier 'uv_async_user_event
_callback_' (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(88): error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(89): error C2146: syntax error : missing ';' before identifier 'uv_async_com_pos_ev
ent_callback_' (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(89): error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(99): error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(99): error C2143: syntax error : missing ',' before '&' (..\src\Callbacks.cc) [C:\U
sers\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(102): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(102): error C2143: syntax error : missing ',' before '&' (..\src\Callbacks.cc) [C:\
Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(104): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(104): error C2143: syntax error : missing ',' before '&' (..\src\Callbacks.cc) [C:\
Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(106): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(106): error C2143: syntax error : missing ',' before '&' (..\src\Callbacks.cc) [C:\
Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(108): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(108): error C2143: syntax error : missing ',' before '&' (..\src\Callbacks.cc) [C:\
Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(109): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Callbacks.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(109): error C2143: syntax error : missing ',' before '&' (..\src\Callbacks.cc) [C:\
Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(50): error C2039: 'ObjectWrap' : is not a member of 'node' (..\src\Context.cc) [C:\
Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(50): error C2504: 'ObjectWrap' : base class undefined (..\src\Context.cc) [C:\Users
\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(99): error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int (..\src\Context.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(99): error C2143: syntax error : missing ',' before '&' (..\src\Context.cc) [C:\Use
rs\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(102): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Context.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(102): error C2143: syntax error : missing ',' before '&' (..\src\Context.cc) [C:\Us
ers\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(104): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Context.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(104): error C2143: syntax error : missing ',' before '&' (..\src\Context.cc) [C:\Us
ers\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(106): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Context.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(106): error C2143: syntax error : missing ',' before '&' (..\src\Context.cc) [C:\Us
ers\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(108): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Context.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(108): error C2143: syntax error : missing ',' before '&' (..\src\Context.cc) [C:\Us
ers\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(109): error C4430: missing type specifier - int assumed. Note: C++ does not support
 default-int (..\src\Context.cc) [C:\Users\Admin\nodeni\build\openni.vcxproj]
c:\users\admin\nodeni\src\Context.h(109): error C2143: syntax error : missing ',' before '&' (..\src\Context.cc) [C:\Us
ers\Admin\nodeni\build\openni.vcxproj]
..\src\Context.cc(40): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\Admin\nodeni\build\openni.vcxproj
]
          C:\Users\Admin\.node-gyp\8.11.1\include\node\v8.h(2453) : see declaration of 'v8::String'
..\src\Context.cc(39): error C3861: 'ThrowException': identifier not found [C:\Users\Admin\nodeni\build\openni.vcxproj]
..\src\Context.cc(40): error C3861: 'New': identifier not found [C:\Users\Admin\nodeni\build\openni.vcxproj]
..\src\Context.cc(68): error C2065: 'handle_' : undeclared identifier [C:\Users\Admin\nodeni\build\openni.vcxproj]
..\src\Context.cc(68): error C2227: left of '->Get' must point to class/struct/union/generic type [C:\Users\Admin\noden
i\build\openni.vcxproj]
          type is 'unknown-type'
..\src\Context.cc(70): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\Admin\nodeni\build\openni.vcxproj
]
          C:\Users\Admin\.node-gyp\8.11.1\include\node\v8.h(2453) : see declaration of 'v8::String'
..\src\Context.cc(70): error C2664: 'v8::Local<v8::Value> nodeopenni::Context::New(const int)' : cannot convert argumen
t 1 from 'const char [6]' to 'const int' [C:\Users\Admin\nodeni\build\openni.vcxproj]
          There is no context in which this conversion is possible
          C:\Users\Admin\.node-gyp\8.11.1\include\node\v8.h(2453) : see declaration of 'v8::String'
..\src\Context.cc(70): error C2664: 'v8::Local<v8::Value> nodeopenni::Context::New(const int)' : cannot convert argumen
t 1 from 'const char *' to 'const int' [C:\Users\Admin\nodeni\build\openni.vcxproj]
          There is no context in which this conversion is possible
..\src\Context.cc(70): fatal error C1903: unable to recover from previous error(s); stopping compilation [C:\Users\Admi
n\nodeni\build\openni.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\Admin\nodeni
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
please help

**Comment by David-Engel** [comment]
@safiahh This repository is not being actively developed. If you are looking for a JavaScript library for connecting to SQL Server, I recommend trying Tedious: https://github.com/tediousjs/tedious
Regards,
David

**Comment by safiahh** [comment]
@David-Engel
Thx for your reply, i am trying to use openni in nodejs and it require node-gyp build when i run it on cmd it shows this error i am using windows10

**Comment by David-Engel** [comment]
@safiahh This repository is not related to openni. It's for node-sqlserver. Maybe you are looking for https://github.com/OpenNI/OpenNI or https://github.com/pgte/node-openni?

**Comment by safiahh** [comment]
@David-Engel I already followed those sites and i had that error the command node-gyp build is not running and gives that error i need to build it to bind between nodejs and openni
