### ISSUE TITLE
msnodesql fails inside iisnode; works on command-line

### ISSUE THREAD

**Issue by schmod** [Azure/node-sqlserver#88]
I have a very small script that connects to, and runs a simple query on a SQL Server 2005 Database using the msnodesql.  

I can run this script just fine from the command line, and everything works exactly as one would expect it to.

However, if I kick this script off from within iisnode, I get the following:

```
iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP reason: Internal Server Error
```

and no further details (node writes nothing to stdout or stderr).  

What the heck is going on, and how can I troubleshoot this further?  I've got the latest version of the module (0.2.0), node 0.8.14, iisnode 0.2.0, and SQL Server Native Client 11.0; all running on Win7 (x64).

**Comment by alejandroLoz** [comment]
Had the same problem and as @jkint said, it was a matter of MSSQL privileges . After I added the IIS APPPOOL user to the database and assigned it with owned schemas and membership it worked.
